language: go
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.5"
  - "1.12.x"
  - "1.13.x"
  - "1.x"
  - "master"

notifications:
  irc:
    channels:
      - "chat.freenode.net#namecoin-dev"
    on_success: never

sudo: false

install:
  - go get -v -t ./...
  - env GOOS=linux GOARCH=ppc64le go get -d -v -t ./...
script:
  - source ./.travis/script
after_success:
  - source ./.travis/after_success

env:
  global:
    # Set this to the Go version to use for releases (must appear in version list above).
    - RELEASE_GO_VERSION="1.12.5"
